Rails.application.routes.draw do
  get 'h_dthread/new'
  get 'thread_chamsg/new'
  get 'thread_dirmsg/new'
  get 'star_messages/new'
  get 'direct_msgcon/direct_msgcon'
  get 'invitations/create'
  get 'joinworkspace/edit'
  get 'joinworkspace/create'
  get 'create_channel/createchannel'
  get 'm_users/new'
  get 'workspaces/new'
  get 'm_user/new'
  get 'all_unread/allunread'
  get 'thread/thread'
  get 'cha_msg/cha_msg'
  get 'dir_msg/dir_msg'
  get 'cha_msgcon/createstar'
  get 'user/create'
  root 'static_pages#home'
  get 'static_pages/createchannel'
  get 'static_pages/invitemember'
  get 'static_pages/msgsendandrec'
  get 'static_pages/mainframe'
  get '/workspace',   to: 'user#new'
  post '/create', to: 'user#create'
  get '/createspace', to: 'workspace#createspace'
  get    '/signin',   to: 'sessions#new'
  post   '/signin',   to: 'sessions#create'
  get '/logout',  to: 'sessions#destroy'
  get '/main',   to:'static_pages#home'
  post '/main',   to:'static_pages#msgsendandrec'
  post '/channel', to:'cha_msgcon#cha_msgcon'
  get '/channel', to:'cha_msgcon#cha_msgcon'
  post '/channelmsg', to:'cha_msgcon#cha_msgcon'
  get '/channelmsg', to:'cha_msgcon#cha_msgcon'
  post '/mentionname', to:'cha_msgcon#mentionname'
  get '/mentionname', to:'cha_msgcon#mentionname'

  get '/channelmsgsend', to:'cha_msgcon#cha_msgsend'
  post '/channelmsgsend', to:'cha_msgcon#create'
  get '/channelunstar', to:'cha_msgcon#unstar'
  get '/chamsgdelete', to:'cha_msgcon#delete'
  get '/channelstar', to:'cha_msgcon#star'
  get '/thread',to:'thread#thread'
  post '/thread',to:'thread#thread'
  get '/allunread',to:'all_unread#allunread'
  post '/allunread',to:'all_unread#allunread'
  get  '/createchannel', to: 'create_channel#createchannel'
  post '/createchannel',  to: 'create_channel#create'
  get '/mentionmember', to: 'cha_msgcon#mentionmember'
  get  '/membermanagement',   to: 'user#member_management'
  get  '/insertfun', to: 'cha_msgcon#insertfun'
  post '/insertfun',  to: 'cha_msgcon#insertfun'
  get '/remove',  to: 'user#remove'
  delete '/remove',  to: 'user#remove'
  get '/removemember',  to: 'cha_msgcon#removemember'
  delete '/removemember',  to: 'cha_msgcon#removemember'
  get  '/test',    to: 'user#test'
  get  '/createworkspaces', to: 'm_users#new'
  post  '/create', to: 'm_users#create'
  post '/directmsg', to:'direct_msgcon#direct_msgcon'
  get '/directmsg', to:'direct_msgcon#direct_msgcon'
  get '/direct', to:'direct_msgcon#direct_msgsend'
  post '/direct', to:'direct_msgcon#create'
  get '/dirunstar', to:'direct_msgcon#unstar'
  get '/dirstar', to:'direct_msgcon#star'
  post '/threadmsg', to:'thread_chamsg#thread_chamsg'
  get '/threadmsg', to:'thread_chamsg#thread_chamsg'
  post '/threadcreate', to:'thread_chamsg#create'
  post '/dirthreadmsg', to:'thread_dirmsg#thread_dirmsg'
  get '/dirthreadmsg', to:'thread_dirmsg#thread_dirmsg'
  get '/dirthread', to:'thread_dirmsg#thread_msgsend'
  post '/dirthread', to:'thread_dirmsg#create'

  get  '/createworkspace', to: 'workspaces#new'
  post '/creatework', to: 'workspaces#creatework'

  get '/msgsendandrec' , to: 'static_pages#msgsendandrec'
  get '/invitemember', to: 'invitations#invitemember'
  get   '/joinworkspaces',  to: 'joinworkspaces#edit'
  post   '/joinworkspace/edit',  to: 'joinworkspaces#create'

  get  '/starmessage', to: 'star_messages#new'
  get  '/directunstarmsg', to: 'star_messages#directstarmsgdestroy'
  get  '/channelunstarmsg', to: 'star_messages#channelstarmsgdestroy'

  get '/dirmsgdelete', to:'direct_msgcon#delete'
  get  '/mentionmessage', to: 'h_mentions#show'
  
  resources :user 
  resources :m_users
  resources :invitations
  resources :joinworkspaces
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
